image: microsoft/dotnet:sdk

options:
  docker: true

pipelines:
  branches:
    master:
      - step:
          name: Build project
          script:
            # Build .Net Core Project
            - dotnet publish -c "Release" ./KitsuneAdminDashboard.Web.sln -o ./bin/Release/PublishOutput
          artifacts:
          - bin/**
      - step:
          name: Deploy to Production
          caches:
            - docker
          deployment: Production
          trigger: manual
          script:
            # Download the necessary tools to deploy to AWS
            - apt-get update
            - apt-get install unzip -y
            - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            - unzip awscli-bundle.zip
            - ./awscli-bundle/install -b ~/bin/aws
            - wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
            - mv jq-linux64 ~/bin/jq
            - chmod +x ~/bin/jq
            - export PATH=~/bin:$PATH
            # Login ECR
            - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            # Build and tag image
            - docker build -t $IMAGE_NAME .
            - docker tag $IMAGE_NAME:latest $REPO_URL:latest
            # push the new Docker image to the Docker registry
            - docker push $REPO_URL:latest
            # Update Task Revision
            - aws ecs describe-task-definition --task-definition $TASK_NAME | jq -c "{containerDefinitions:.taskDefinition.containerDefinitions}" > task_def.json
            # register the ECS task definition and capture the version
            - export TASK_VERSION=$(aws ecs register-task-definition --family $TASK_NAME --cli-input-json file://./task_def.json --region $AWS_DEFAULT_REGION | jq --raw-output '.taskDefinition.revision')
            - echo "Registered ECS Task Definition:" $TASK_VERSION
            # Update the ECS service to use the updated Task version
            - aws ecs update-service --cluster $CLUSTER --service $SERVICE_NAME --task-definition $TASK_NAME:$TASK_VERSION